version: '2'
services:
   mysqldb:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=consent
      - MYSQL_USER=consent
      - MYSQL_PASSWORD=consent1234
    ports: 
      - "3306:3306"
